#!/usr/bin/env bash

set -Eeuo pipefail

NATIVE_SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(CDPATH= cd -- "${NATIVE_SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${DUB_NATIVE_ENV_FILE:-${PROJECT_ROOT}/.env.native}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # The environment file is administrator-owned configuration.
  source "${ENV_FILE}"
  set +a
fi

export PROJECT_ROOT
export DUB_NATIVE_ROOT="${DUB_NATIVE_ROOT:-${PROJECT_ROOT}/var}"
if [[ "${DUB_NATIVE_ROOT}" != /* ]]; then
  echo "DUB_NATIVE_ROOT phải là đường dẫn tuyệt đối" >&2
  return 2 2>/dev/null || exit 2
fi

export DUB_DATABASE_PATH="${DUB_DATABASE_PATH:-${DUB_NATIVE_ROOT}/state/jobs.sqlite3}"
export DUB_MODELS_LOCK_PATH="${DUB_MODELS_LOCK_PATH:-${PROJECT_ROOT}/config/models.lock.json}"
export DUB_MODELS_DIR="${DUB_MODELS_DIR:-${DUB_NATIVE_ROOT}/models}"
export DUB_INCOMING_DIR="${DUB_INCOMING_DIR:-${DUB_NATIVE_ROOT}/data/incoming}"
export DUB_JOBS_DIR="${DUB_JOBS_DIR:-${DUB_NATIVE_ROOT}/data/jobs}"
export DUB_OUTPUT_DIR="${DUB_OUTPUT_DIR:-${DUB_NATIVE_ROOT}/data/output}"
export DUB_GPU_REPORT_PATH="${DUB_GPU_REPORT_PATH:-${DUB_NATIVE_ROOT}/state/gpu-health.json}"
export DUB_PROWLARR_API_KEY_FILE="${DUB_PROWLARR_API_KEY_FILE:-${DUB_NATIVE_ROOT}/secrets/prowlarr_api_key}"
export DUB_QBITTORRENT_PASSWORD_FILE="${DUB_QBITTORRENT_PASSWORD_FILE:-${DUB_NATIVE_ROOT}/secrets/qbittorrent_password}"
export DUB_OPENSUBTITLES_API_KEY_FILE="${DUB_OPENSUBTITLES_API_KEY_FILE:-${DUB_NATIVE_ROOT}/secrets/opensubtitles_api_key}"
export DUB_OPENSUBTITLES_TOKEN_FILE="${DUB_OPENSUBTITLES_TOKEN_FILE:-${DUB_NATIVE_ROOT}/secrets/opensubtitles_token}"
export DUB_OPENSUBTITLES_BASE_URL_FILE="${DUB_OPENSUBTITLES_BASE_URL_FILE:-${DUB_NATIVE_ROOT}/secrets/opensubtitles_base_url}"
export DUB_PROWLARR_DATA_DIR="${DUB_PROWLARR_DATA_DIR:-${DUB_NATIVE_ROOT}/prowlarr}"
export DUB_QBITTORRENT_PROFILE="${DUB_QBITTORRENT_PROFILE:-${DUB_NATIVE_ROOT}/qbittorrent}"
export DUB_PROWLARR_BIN="${DUB_PROWLARR_BIN:-${DUB_NATIVE_ROOT}/opt/prowlarr/Prowlarr}"
export DUB_RUNTIME_RUN_DIR="${DUB_RUNTIME_RUN_DIR:-${DUB_NATIVE_ROOT}/run}"
export DUB_RUNTIME_LOG_DIR="${DUB_RUNTIME_LOG_DIR:-${DUB_NATIVE_ROOT}/logs}"
export DUB_NATIVE_USER="${DUB_NATIVE_USER:-dub}"
export DUB_API_HOST="${DUB_API_HOST:-127.0.0.1}"
export DUB_API_PORT="${DUB_API_PORT:-8080}"
export DUB_API_URL="${DUB_API_URL:-http://127.0.0.1:${DUB_API_PORT}}"
export DUB_PROWLARR_URL="${DUB_PROWLARR_URL:-http://127.0.0.1:9696}"
export DUB_QBITTORRENT_URL="${DUB_QBITTORRENT_URL:-http://127.0.0.1:8081}"
  export DUB_QBITTORRENT_USERNAME="${DUB_QBITTORRENT_USERNAME:-dub}"
  export DUB_VENV_DIR="${DUB_VENV_DIR:-${PROJECT_ROOT}/.venv-native}"
  export PATH="${DUB_VENV_DIR}/bin:${PATH}"
export DUB_DEFAULT_ASR_MODEL_ID="${DUB_DEFAULT_ASR_MODEL_ID:-asr-faster-whisper-large-v3-turbo}"
export DUB_DEFAULT_TRANSLATION_MODEL_ID="${DUB_DEFAULT_TRANSLATION_MODEL_ID:-mt-gemma4-31b-q4}"
export DUB_DEFAULT_SEPARATION_MODEL_ID="${DUB_DEFAULT_SEPARATION_MODEL_ID:-separation-tiger-dnr}"
export DUB_DEFAULT_TTS_MODEL_ID="${DUB_DEFAULT_TTS_MODEL_ID:-tts-vieneu-v2}"
export DUB_TTS_SUPPORT_MODEL_ID="${DUB_TTS_SUPPORT_MODEL_ID:-tts-neucodec-onnx-int8}"
export DUB_TIGER_SOURCE_DIR="${DUB_TIGER_SOURCE_DIR:-/opt/tiger}"
export DUB_VIENEU_ENTRYPOINT="${DUB_VIENEU_ENTRYPOINT:-/opt/vieneu/vieneu-offline.py}"
export VIENEU_CODEC_PATH="${VIENEU_CODEC_PATH:-${DUB_MODELS_DIR}/tts/support/neucodec-onnx-int8}"
export PYTHONPATH="${DUB_TIGER_SOURCE_DIR}:/opt/vieneu/source/src${PYTHONPATH:+:${PYTHONPATH}}"
export DUB_ASR_COMPUTE_TYPE="${DUB_ASR_COMPUTE_TYPE:-float16}"
export DUB_ASR_LANGUAGE_CONFIDENCE_THRESHOLD="${DUB_ASR_LANGUAGE_CONFIDENCE_THRESHOLD:-0.5}"
export DUB_OFFLINE_WORKER_POLL_SECONDS="${DUB_OFFLINE_WORKER_POLL_SECONDS:-1.0}"
export DUB_LLAMA_SERVER_BINARY="${DUB_LLAMA_SERVER_BINARY:-/usr/local/lib/llama.cpp/llama-server}"
export DUB_LLAMA_SERVER_PORT="${DUB_LLAMA_SERVER_PORT:-18081}"
export DUB_LLAMA_CONTEXT_SIZE="${DUB_LLAMA_CONTEXT_SIZE:-2048}"
export DUB_LLAMA_MAX_OUTPUT_TOKENS="${DUB_LLAMA_MAX_OUTPUT_TOKENS:-512}"
export DUB_LLAMA_STARTUP_TIMEOUT_SECONDS="${DUB_LLAMA_STARTUP_TIMEOUT_SECONDS:-300}"
export DUB_LLAMA_REQUEST_TIMEOUT_SECONDS="${DUB_LLAMA_REQUEST_TIMEOUT_SECONDS:-180}"
